module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DUPLICATE_LEADS: "DUPLICATE_LEADS",
    ASSIGN_LEADS: "ASSIGN_LEADS",
    ASSIGN_TO_ACTIVE: "ASSIGN_TO_ACTIVE",
    ASSIGN_TO_INACTIVE: "ASSIGN_TO_INACTIVE",
    ASSIGN_TO_TOTAL: "ASSIGN_TO_TOTAL",
    STATS_LEADS: "STATS_LEADS",
    ASSIGN_TO_SINGLE: "ASSIGN_TO_SINGLE",
    CHANGE_TL: "CHANGE_TL",
    ASSIGN_TL: "ASSIGN_TL",
    ASSIGN_HR: "ASSIGN_HR",
    ASSIGN_TO_TL: "ASSIGN_TO_TL",

    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    DELETE_ALL_LEAD: "DELETE_ALL_LEAD",
    MEMBER_DELETE: "MEMBER_DELETE",
    MERGE_WEBSITE_LEADS: "MERGE_WEBSITE_LEADS",
    WITHDRAW_LEADS: "WITHDRAW_LEADS",
  },
});
