
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DUPLICATE_LEADS : "DUPLICATE_LEADS",
        ASSIGN_LEADS : "ASSIGN_LEADS",
        // ASSIGN_TO_ACTIVE : "ASSIGN_TO_ACTIVE",
        // ASSIGN_TO_TOTAL : "ASSIGN_TO_TOTAL",
        // ASSIGN_TO_INACTIVE : "ASSIGN_TO_INACTIVE",
        ASSIGNED_CHOSEN : "ASSIGNED_CHOSEN",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        MEMBER_DELETE : "MEMBER_DELETE"
    },
});

